services:
  - type: web
    name: edencalc
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: APP_ADMIN_CNPJ
        sync: false
      - key: APP_ADMIN_SENHA
        sync: false
      - key: APP_SEED_DEMO_DATA
        value: "false"
